
//String methods 
let name="John Doe";
console.log(name.length);
console.log(name.toUpperCase());
console.log(name.toLowerCase());
console.log(name.slice(0,4));
console.log(name.charAt(3));
console.log(name.indexOf("o"));
console.log(name.lastIndexOf("o"));
console.log(name.search("o"));
console.log(name.repeat(3));
console.log(name.split(" "));
console.log(name.substr(3,5));
console.log(name.substring(3,5));
console.log(name.replace("o","a"));
console.log(name.replaceAll("o","a"));
console.log(name.concat(" is a coder"));
console.log(name.trim());
console.log(name.includes("John"));
console.log(name.startsWith("John"));
console.log(name.endsWith("Doe"));
console.log(name.charCodeAt(3));
console.log(name.charCodeAt(3).toString(16));
console.log(name.trimStart());
console.log(name.trimEnd());
console.log(name.padStart(10,"*"));
console.log(name.padEnd(10,"*"));
console.log(name.match("John"));
console.log(name.matchAll("John"));
console.log(name.typeof);
